language: python
sudo: false
python:
- '2.7'
- '3.6'
- '3.5'
install:
- pip install --upgrade tox-travis -r requirements_build.txt -r requirements_doc.txt
script:
- tox
- sphinx-build -b html ./doc built_docs -E -W
deploy:
  skip_cleanup: true
  provider: script
  script: python scripts/release.py $TRAVIS_TAG
  on:
    branch: master
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = "2.7"
notifications:
  on_success: always
  on_failure: always
  email: false
  slack:
    secure: Dvy6Gg/6XHNsfG5T6o4uvTVsxxzdpfMczpP71bZ5Q5JA4s7OjI4+OIAXc7UOb03TQL8HyLG4SF96osbvUVakg9fe3NbwcC1bxI6aNufCN5JDbKAjh0pAndugAoDX+m1sMZDcov3XqiMms+QHDQT2ecS4PgTGSNTLoIxnIXeya2dSJOxKYk1DzAugR124we5PGb3cZo/PatxRTGStbFtfhXHKy984wdMXXUGEu0M+ZLDrafcPL9emywd+8aUmc1gg5e6WrnCEuXhwEHe+P5Rre3//0BaqtGjT2yuwLz8IaFksYX9cLIEyMlrhteL6d1sillUiNLTRAhRdv7PLDxlaLDXI0Yn0y3TR2Y2erXf5tsOIoC8cKnjpO8TJ47LkceTde+z+Byz48dII8KNmu2LicaLv2NUGI+EMKkZdVk3Z5PdEGtKALs0wsBbdEZZcrUioP0dXSgIC/bDMVZtEGHaZyeNj9+MxyYKSJfAYuDg/KQN39hVsR7DZu6T+WB4wIwSEth4GSI5GcVvXi8FB6IGUolxTOzI6cRxlc4LG0AKN20OJyNrRlaqYNH2WNqtAdtHUWaLDMPzGz/a0A35cqr9I1PkiXKAAm+G/IheSq4bszNYtMFzEJcsVetWvuNCcOCJ+xlsVDi3VHWjo9QFOoAPAWHvOdq1vHQiV0codiwH55Bg=
