jobs:
  include:
    - stage: Test
      os: osx
      language: sh
      python: "3.6"
      name: "Mac OS - Python 3.6"
      addons:
        homebrew:
          packages:
            - python3
      before_install:
        - python3 -m pip install --upgrade pip wheel virtualenv
        - virtualenv venv -p python3
        - source venv/bin/activate
        - python --version
    - os: osx
      language: sh
      python: "2.7"
      name: "Mac OS - Python 2.7"
      before_install:
        - python -m pip install virtualenv
        - virtualenv venv -p python2
        - source venv/bin/activate
        - python --version
    - os: windows
      language: sh
      python: "3.6"
      name: "Windows - Python 3.6"
      before_install:
        - choco install python3 --version 3.6.5
        - export PATH="/c/Python36:/c/Python36/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel virtualenv
        - python --version
    - os: windows
      language: sh
      python: "2.7"
      name: "Windows - Python 2.7"
      before_install:
        - choco install python2
        - export PATH="/c/Python27:/c/Python27/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
        - python --version
    - os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Linux - Python 3.6"
    - os: linux
      dist: xenial
      python: "2.7"
      name: "Linux - Python 2.7"
      language: python

    - stage: "Deploy"
      if: branch = master AND type != pull_request
      script: python .multipackage/scripts/build_documentation.py
      os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Documentation to Github Pages"
      deploy:
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          committer-from-gh: true
          keep-history: true
          local-dir: built_docs
      env:
        - secure: SYbsOUUnOLpfjNJbsV9vYbwCsJIVFrFVVRS3+a1rJ5DWZoo64EySKfq1TsCST/k4E3+xv3kbylVmB1Uogrqi4gyJjhvvIqKyz5uKeMPY7Wv9KuDvBlGBu10X65lmE+JPV1fcTm0nfOi5s/JqX9mRZVT6hyYZFP5SildXa0JghZsjYsL5V1ykYKdER2g98ctnsq3uZ/0vHyLC6q3VX0X47Q4Y0SMwWv1ah8qC1EknPcubj05XZrAWFLLqfthtOHAWStEaTcQzeWY41C9ZqorH9ljfMd+XQXfoty+M5L4h/acnNLlnkleSBnlOMvRatIws9x6Hx0g/Au4YgFgic/9v1ebKKjI1thzXgHO8RUkm92LLtCfpeze45+TPCeRie+7tHWlZTrVJg3di/E4jxw3vDmPWrdMV94Jl27Q1+Zgd0BQ8utuFYVdi0s/EbHsYqIfThUkS3lF/ebMY2yrumtGRB2SeSu8yfAqtwkUaNVKnOJnbzAozvf1Oy5wQOmyhQQRfumDltuoyipTuLnIjgRlkNU8MiqL4lHcWy4YIx1Ec+T/avCOq5S3++Q3rPQ5zTDo7Bj1UFFxpQuKG8lrJcHD7Da/SoeuqJkKDJ0PHhmEOS3S0jkVc5sOPbyKK4yLIKKO0xZTgpIwBo9npMt9OLQcwIOyp1p8ggwExWG44u7iyU/Y=
    - stage: "Deploy"
      if: tag IS present
      script: python .multipackage/scripts/release_by_name.py $TRAVIS_TAG
      os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Release to PyPI Index"
      env:
        - secure: terQF4zOfzRYolpOYn0+fezwYE//nQbrgZlQT377Kh/lBULP8P7B1vjVdI6B2JYTxNkw3YNcPt+vGvzW5MdzRHPtVpokKRi0rCpPLKkJ+9AgRxGfK8meikEzT0mR4K5WwJLCIxUO6NJAGllPWKsThwhZ9nAKGuQMePD0WsOaXrLHAGuvO4qd7ImRYJv9XcCPbXmXQhE+0eYJSaHXQqsHR/IIF2GJ9wBVIkXRyi1eLRIES1KDwtWa0Q6TNj8syV8bUY4rA6gPejfuVuGwPZvJczSRFQKv9N84Qky4nHuDtT0YvjphI7WPcT/Q/7dSxjza73Yo6VQriAoax77s5ytLmXgIquCVKnRWG3aocfqeG/U0zypP4lzWAnPzmLiR021wWublJY1bAGAowmUAb4EOh5IdeJgxoa2q4KgUF2eY++TsFMWR9ZAGBfOTg91s6cu7Hi8WPpu1aD0jlVhy/AOlSrkkEzTt83AQK7GJTW0mE3OTHjeDoSOD8a3QX0vW1ZqjNrBczt7VCk9zvoe4bLcBiFPDiX7t57Gcg0OmUS5x4tNW1z9gllfxnXGeD8k3fYfDGnH39eVKsanPQORWRMvWfmococRixQAWgumIMa2GxQ3MNRl2DUmTjTCrbUMolBRAEcnSdj7fV7LZfd+mvsUe6dbT+WPM3c7KI802dBvYd88=
        - secure: r2aMibrCkqf7Ixmhjaei024ktqk4jNHhmTCihuAKMM4h+FnitiYQHBYm8+QudSNX/y+MyH8/+nAGIgi6G29VDQEdLKspOvTs8Om96jsU5GRJ2GG0S7Cq15AKoW9Z1v2OcJ6H1upkElJ3uuIn3D09jdb1YFs7DvJy2lfrpt+kKXDBY+Tt8ItKcaL0K0CWVS4H0iPQwO8Ri9waBH5ogVcjxZ7scUmIlmxsyCuVUGmWrLjhroAKmBjVks75WWs3UW1LR4HhyaeKm47cM4XyEieePAgwUTaaCu1EYhteh8G/g2ipACIaUnuaHlmRREuQvP5ipyQA8CuW2xD8b+eNUdISprzHXAVZ/otxKgI/6V27MR8SEqzap65RTq12PWsJAfhfnIfuvhAXa9z/EWbRsTAAwDzYdJP4UHNackY1TE5e1/m6U6PNe8nEZi9iI84gjuRadkPMFlD0wvC1n0ZMk4cBextTYckioT4CEu5gkoFgVdOXbQdXdhNHbs/kvpW9F3wwcIHfzW55P1hGsZtm0pFSVsr6FXsXwZ7nVxKUc4epV0KZ8t6cOaaYOOE4mALksTFciw8Uivhj2LDW4CXZj4gk84FN3oG6AzBB1rgkaY07YWokc+WfnopoEM5Uou+JbrAe73rb5G5cl47gakpgdJ/HENNgIqVjVq/oXX8TpFLC5Xg=
        - secure: JDwbyKHwpPIKrnrV7B0Slpt/Vp/s3LjRHtOeZLYbWCtRST3AINCRtYgXvKVmZjoHJ8LQKB4VMTwuXzffY2TtvxJi+zo4NUSGiK4c9EGhWxYRg1BAb+FYSSqPV1OW0GD7WDvTeVRHSY/IhLc872WzD0mYdbxndvVloHK+oWMocJyhNyqHSMuOZy1mYLHJJJucawOxkT8YW2kl6uU6wrLGU2t8CdDie0JF4Sbd4wE80bY+cwAt3g4CBQKt1VWoFiFZV6x5UGI7rU6m+wtUfXMfFkXHPFf46lIlH84pQJDMsVsW2vY2z766BLIJoy3ImuS41ttxsakFqSswkx1ICKF/BZeBfixIa4/XBhduLkoWDpLdPbvVxC/uhX4cME2JtJu8cHngZ4mxzNaTha6rVCz5Cz2ljcCmfikrZthis644V8O4z60OENKNSChjLYvMGfm3qh4opw6rRZSrRHzL5EjN1NrYt+ZUiHmN86Q2GdUxCZn5ArFHdgdvndQKpR8Nh/+CNhrIiyisoQtcxO1I4Z9xsdxuqmROwV2sIxiB8B99q6DzDEWluda+IS/8uv6iBQTiSGE5lBVlL/xidnzK2ILaus9qfip8FpeptBS5fz0vG575J4p2YUrjSSfF2kWCBUgXvlx81A6CcL6n91BeyQ9d5ryHc/+TPlwa4exPXBb10xk=

install:
- pip install -r requirements_build.txt -r requirements_doc.txt
- pip install ./iotile_analytics_core
- pip install ./iotile_analytics_interactive
- pip install ./iotile_analytics_offline

script:
- cd ./iotile_analytics_core && pwd && pytest test
- cd ./iotile_analytics_interactive && pwd && pytest test
- cd ./iotile_analytics_offline && pwd && pytest test
- python .multipackage/scripts/build_documentation.py

notifications:
  email: false
  slack:
    rooms:
    - secure: OWjd2aySWbzYCYWvUA3tio1abDyKmk/40uxfLOC6yyx3H4AhdHvyUkwMxEs6tlO+DxcXWLxhK+9k39AdygLcNxgmYGbqdINauwP2X1ZUPo8zTuCDw3M0XJIXckRdifQYkvld5zq6ecyKPhn+LYPBR+gbclBqxtoPFejxc42fWbbEAioPE2f2nYLUFWX+hJKTYRTjmOi6hnu8I2TqQ13AjX+EAPi9Juep/QrQ5lzQh0WsbmSNMHeQQmQXygbWJvQ7rcxUu/zzop+MV8vK3G7IIZNTL0dSBO8cO+iIxFBWzuscHFH9K7a/Zf/3J4/M8domTgQNVKFAcZxt44cC6pGdE69yjcyt4w8wEg/T6o7KN8cmr20Rpud47SHlU6JCKeJtbi/aiq9Fklh2dC0CM0VzrpJgfEKTP+YVZ29BAPnOgae/uLfEp9jIfIeUaUQLlC6hgfgDxkyVUjpNWwdG8VvZnwztnUn8++2u9ciXylmL0hYSvCAbrslKQyfrV/To1f9dUEEcA2TDDAVM9YYs0/iIsoq8qIQt05A7YCJ0ThCdVLHzm0BUPZlpRWUoTlVZz1CLc2gQt6mwyfSiKZkChsiAEwKTaUxKzn/bitRNnKorcX1WQ6MBT1VkPMeT4pprWhvOtLK1m5JA3sgV/GOjNES05phzkY9Hbn7jRop5ZKQDR10=
    template:
    - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch} in PR <%{pull_request_url}|#%{pull_request_number}> by %{author} %{result} in %{elapsed_time}"
    on_success: always
    on_failure: always