jobs:
  include:
    - stage: Test
      os: osx
      language: sh
      python: "3.6"
      name: "Mac OS - Python 3.6"
      addons:
        homebrew:
          packages:
            - python3
      before_install:
        - python3 -m pip install --upgrade pip wheel virtualenv
        - virtualenv venv -p python3
        - source venv/bin/activate
        - python --version
    - os: osx
      language: sh
      python: "2.7"
      name: "Mac OS - Python 2.7"
      before_install:
        - python -m pip install virtualenv
        - virtualenv venv -p python2
        - source venv/bin/activate
        - python --version
    - os: windows
      language: sh
      python: "3.6"
      name: "Windows - Python 3.6"
      before_install:
        - choco install python3 --version 3.6.5
        - export PATH="/c/Python36:/c/Python36/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel virtualenv
        - python --version
    - os: windows
      language: sh
      python: "2.7"
      name: "Windows - Python 2.7"
      before_install:
        - choco install python2
        - export PATH="/c/Python27:/c/Python27/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
        - python --version
    - os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Linux - Python 3.6"
    - os: linux
      dist: xenial
      python: "2.7"
      name: "Linux - Python 2.7"
      language: python

    - stage: "Deploy"
      if: branch = master AND type != pull_request
      script: python .multipackage/scripts/build_documentation.py
      os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Documentation to Github Pages"
      deploy:
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          committer-from-gh: true
          keep-history: true
          local-dir: built_docs
      env:
        - secure: U8R3nGVwfZenBmh5AWm5Z6SEGlGS9X4zkUcindQHRMwGX57Z59JlDvz2iz+ERZ5JExF37PIttsy4RQdz/bLLS1Rr4ubg9gVLyRc4f+e8fBmP06J3BiQpwwo/uYE4knlhbVdtj58cBqj9czViaq1um1rBXMZk8Jk1BAz8JkLNY9CZCoHkaQNcxx/cdAdgTSgCUjUld/gd4il63TpXbJ7vikIgApwzp0tY/BhnKbXoK1tqWLgBm5AM0m+4+mmV3FV77LZtz1FPWge53MNsQiytGREAJ4WA5Z1f7LASXPbuGOQBgnMW/aQjP49lzBONax9Cyd0Lj2+DQQcLCzEnBu57vDhfhb1lvU555BSzznCjBFosu6mbOgVO5YPOryol6F64O7B8uTu95p+hoJqEtfkorjCVtffzVNZIh1hvvlDwCjs2QPrial1VQvyhVCVcDSSMb7kkFN0iO3fzuIhPKJMv2fWTp29XBlrPzZgrZF/wsodF4cJFSr3dEtT4EX1d6/xHm2y72qOuEsGLyvLHlv4RxRPe8welcy3KMdFe3d1EnWvfKISbElRSFzNgfIC27RZDGQsds5C23UfSOS0/wjlVZc5UfoYOCimXinxPqRZ6n91TaszMS6S/xKABkXTWhrLEdIepRuJIjBXxSVzDLpIq/35AH452q83xrrlMQ/smFdc=
    - stage: "Deploy"
      if: tag IS present
      script: python .multipackage/scripts/release_by_name.py $TRAVIS_TAG
      os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Release to PyPI Index"
      env:
        - secure: nXVx4tmyHTziX+1sRbZzWxanDfkTbxY1gSslUeFineYdREjBxhnnxuePTCQsAiMuWZZOwX5AoMBPD2hgHtnhcJRxfA+YR6iJ/OzJj5HJhQYUUYgi/0orzy1/Z/S2Sq5WV3Xjn6ibRr5NUsAmmkn2poxlkSFKU/tWzHSY3Uw9rHhSkhNaGPUlqpOvaEgzrpz3E4VqsTiN3w8bMT7L06++VNE9T6uYSPBCML06RDJhAYS/jPWaT7aAX7ZDjLGqUXbSO8WSZSoc6I5wQNh3VRkuniqzYXl69Mr2aorx7NhHrp9AKI0I6Qge5jnRKOV+58csttx6U262hL/p19qNbAaxlzddWf5DIXD6cUi7BuITcG8KACbdniKLgxlavFBA24HkRe2ASYJ5jyBI2J/2dvr1kG+hnwhnwvYTnpefjkMMjgLEhB5jHq2h3ZGX19Ds0QnapHZVosI7cbAygX4/hwsTUXrAN5TuMZUjUqTeySwxw0drZ1mp+kyUSz+fP/rUqwIHPQ47i+g7hg6VmKqOeWvkTF+ifrDJezYL2IzQdcNUWt2qRmWbFrgXHLuYxK3Xqha1BaaA0dQvgcKX5CGWmxmeYlxJJKGJYHFoEz9nf5f01uIeMlEweyBpLKS+z3yoJy1oBeGxMVDL8HFJu+l/0OxuKjsC1RyL40+x+N22oQLWxJ0=
        - secure: kwMGABWrDxD2UgNjBP6Gna20KTxzstADTYQJnrcPoVPOAFU/aZuK6BbGNbyfGVApgioCE8F5u7qpmkq+MrwzLrtiqDvc59wI5lsGfqKoQ/aPiP7R1aqCzza52v4S7z+ppb6oUFykGAoX/Q2Xax1VLEq9Mn16LxMOHNEtGOpKyRjt0kpUpEW4SpFvKzZ9THdWCfhRaTJhytOWcqss1ep/nNWh6vMX/B4CeNbeCnlwp+7MJmUp8f2akgwRi28JlHhysO7KaX6Lcm0p7s3baZ9/Mrph5QkBUGSojLQ/krHSDpwEnvNJcQuzLHTQQAulDqUQwJTg8tOQgaTnXS8NGvKuujb6S/1D4mmXsa2z+8IhhaAWlstqmqkY/UiksF26AQhu1qLlUxr78PMkbhwZeuie0bTMQpqgFevugQvd45yTvM50Y5P7hfwX6NriJp22DAslqTWoGu+vkzI1ZlX8BWvyk3Ah5ln9ybOsXn4bG7inaAIsz96jmWf3KHSqBCPBEiLXttQtZkY15Xx+o6PibvxcXwIx126TowgBGg/hbFSQifLVHHuvUvOcrlir377yQ+4kGuFzRAO8XRfyoMqIBckAzUZcOX82+kpL4lTmH/9p2CQPeZPIPNU89kaoGph2YLEvjLAdo8dE/aoVbve24mfgLWwIzTSMnkK0+dvM2tCcB68=
        - secure: JHM0Z2UcrvFR4F73oGRHIIf4sChVflMZ6us6a3JSWZIG5x/tKIpXwt+UBbGLaNJPq1YCr4UfEltcfiEaI/g8BXCZyOTP45iz3vaW+KiRaKz4NiVtM9+uU+bbezduwXIG6KCCBWbHrSzFidehtzXRkNBSxB5KXXhhvjKu8QxE6U6iKBuhPQ4UnKFhd0OcO8AnjJVyx75VICI3HgLKrxA7al4hulUR5A+Vz1RgpsvJQo92VKy4u51T8cvjG9DWWVam2jLypn+Qd+R9XpV2NgBot383/sSgOOHAxAV/HfqKxS0Sj13h2XwabmRDdkPXSK7AR4p6cOkQCVEFtYCg0YOgmaEcbX+3HYJzBgeEb8gT+y8U7uFss2PPrtoyhiSE2o0bijzD5gyN9DLJSzPc1q1+ZfyPKmvg928dXYOwkmImR4ZIxnGoEX62tBwkazokRwzAttoEIvSWJDhZYmyxY7S3699fpaM505hpDlC3IHcoqJzy69cyrh9uXaQ/WhL3DmrVDxpR9Ju0tMZ/rRYWVOegfnX7gYV5bDQPr2t42kWV3TSZE94Nuly13rb+SSe2/5bDDmXT8k4UPHcvSK/DftSF8JB0suICiMDjS2z7gJbI7volMjC2lEJ146ap663aVNkjV4VyWgprK8ANSNvq8Gvq4p7D+jkue+dlDed5U/Q3DrQ=

install:
- pip install -r requirements_build.txt -r requirements_doc.txt
- pip install ./iotile_analytics_core
- pip install ./iotile_analytics_interactive
- pip install ./iotile_analytics_offline

script:
- bash -c 'cd ./iotile_analytics_core && pwd && pytest test'
- bash -c 'cd ./iotile_analytics_interactive && pwd && pytest test'
- bash -c 'cd ./iotile_analytics_offline && pwd && pytest test'
- python .multipackage/scripts/build_documentation.py

notifications:
  email: false
  slack:
    rooms:
    - secure: p6MOq7bhum3KIEVCT79LnPeDJGC+tM6j9985FCqxSLa7Bpb5KpQsdQVz08Wm2pcSOlD5X9TSTCvZVWTfNTXbs9aPFrTuogCqQ4OftCaBm/RFKr4ePXcRadgPYjUUFtZuj8YnHAzoSOH1bhl2K8M6i9zYZ80iCVoVABjl/GkAQ1+vI0cpyky9PGl6+CPVZLYSrJrNP/7FvBhz6sZY33sZim0wRt5JJXKqkse2E45pEq154XUccj7+WEFE2Gf9muBZkkbRz+owgAnIHGwKLVcOnpvX2vq/XaXxBdg5Wi5hwYvHnFbIU/kiER+GtUluSM/Oulhj8BHUxbOuWcTF6sS7xzLKVj0p22ouwCG1NW2pfjXPc9anF+NSCmfZHhNZmidFxcrpR1L1e34jZ30wzOpiORYYlyIe1wKZtKVVffisdOyCH3CD0N3jaQeHWpwEFMEbpOADvWRxB79yMftjvTPLe46aeoEvb8YzpSKRWZbIsJFwtZm3NnMuyUokCUVR5N38NAvdXX+tId94+PvHYajK6BDMkDiGeAVeONQC4Q37jEFfMPNECUFqx4aavdxJ8ZJz6Afe0kfZ9tta/AoOnhZgx4IY7yQQVsv8l2pFkjomX8aViDHjExjXzSkoiZznN78kQzsvoz7wYc8ErjpvgyoA3PpE68EFoey62ZaLNtrLkZo=
    template:
    - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch} in PR <%{pull_request_url}|#%{pull_request_number}> by %{author} %{result} in %{elapsed_time}"
    on_success: always
    on_failure: always