language: python
cache: 
  pip: true
sudo: false
python:
- '2.7'
- '3.6'
- '3.5'
matrix:
  include:
  - python: 3.6
    env: BUILD_DOCS=1
install:
- pip install --upgrade tox-travis -r requirements_build.txt -r requirements_doc.txt
script:
- if [[ "$BUILD_DOCS]" != "1" ]]; then tox; fi
- if [[ "$BUILD_DOCS" == "1" ]]; then tox -e docs; fi

deploy:
  - provider: script
    skip_cleanup: true
    script: python scripts/release.py $TRAVIS_TAG
    on:
      branch: master
      tags: true
      condition: $TRAVIS_PYTHON_VERSION = "2.7"
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: built_docs
    on:
      branch: master
      condition: $BUILD_DOC = "1"

notifications:
  on_success: always
  on_failure: always
  email: false
  slack:
    secure: Dvy6Gg/6XHNsfG5T6o4uvTVsxxzdpfMczpP71bZ5Q5JA4s7OjI4+OIAXc7UOb03TQL8HyLG4SF96osbvUVakg9fe3NbwcC1bxI6aNufCN5JDbKAjh0pAndugAoDX+m1sMZDcov3XqiMms+QHDQT2ecS4PgTGSNTLoIxnIXeya2dSJOxKYk1DzAugR124we5PGb3cZo/PatxRTGStbFtfhXHKy984wdMXXUGEu0M+ZLDrafcPL9emywd+8aUmc1gg5e6WrnCEuXhwEHe+P5Rre3//0BaqtGjT2yuwLz8IaFksYX9cLIEyMlrhteL6d1sillUiNLTRAhRdv7PLDxlaLDXI0Yn0y3TR2Y2erXf5tsOIoC8cKnjpO8TJ47LkceTde+z+Byz48dII8KNmu2LicaLv2NUGI+EMKkZdVk3Z5PdEGtKALs0wsBbdEZZcrUioP0dXSgIC/bDMVZtEGHaZyeNj9+MxyYKSJfAYuDg/KQN39hVsR7DZu6T+WB4wIwSEth4GSI5GcVvXi8FB6IGUolxTOzI6cRxlc4LG0AKN20OJyNrRlaqYNH2WNqtAdtHUWaLDMPzGz/a0A35cqr9I1PkiXKAAm+G/IheSq4bszNYtMFzEJcsVetWvuNCcOCJ+xlsVDi3VHWjo9QFOoAPAWHvOdq1vHQiV0codiwH55Bg=
